name: rickmorty
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  bloc_test: ^9.1.3
  easy_localization: ^3.0.7
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: any
  material_color_utilities: 0.8.0
  shared_preferences: ^2.1.2
  stream_transform: ^2.1.0
  meta: ^1.9.1
  searchbar_animation: ^0.0.4
  flutter_moshimoshi:
    git:
      url: https://github.com/fsalom/flutter-moshimoshi
      ref: 1.0.2
  mirai_trace_logger:
    git:
      url: https://github.com/WilliamAndreu/mirai_trace_logger
      ref: 1.1.3
  dartz: ^0.10.1
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  test: ^1.24.1
  mocktail: ^1.0.4
  mockingjay: ^0.5.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  mockito: ^5.4.4
  mason: ^0.1.0-dev.57



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
  - lib/core/assets/images/
  - lib/core/assets/translations/

  