name: rickmorty
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.6

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_moshimoshi:
    git:
      url: https://github.com/fsalom/flutter-moshimoshi
      ref: 1.0.8
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  hybrid_logger: ^1.0.4
  injectable: ^2.5.0
  intl: any
  material_color_utilities: 0.11.1
  meta: ^1.9.1
  searchbar_animation: ^0.0.4
  shared_preferences: ^2.1.2
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  injectable_generator: null
  mason: ^0.1.0-dev.57
  mobx_codegen: ^2.1.1
  mockingjay: ^1.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  test: ^1.24.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/images/
    - lib/core/assets/translations/
